//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdDJ_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partytweet
    {
        public int PartytweetID { get; set; }
        public string Message { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PartyID { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual User User { get; set; }
    }
}
