//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdDJ_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteID { get; set; }
        public byte[] Timestamp { get; set; }
        public int UserID { get; set; }
        public int TrackID { get; set; }
    
        public virtual Track Track { get; set; }
        public virtual User User { get; set; }
    }
}
